import type { Config } from "tailwindcss"

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      animation: {
        "scale-up-down": "scale-up-down 0.25s ease-in-out",
      },
      backgroundImage: {
        "gradient-radial": "radial-gradient(var(--tw-gradient-stops))",
        "gradient-conic":
          "conic-gradient(from 180deg at 50% 50%, var(--tw-gradient-stops))",
      },
      colors: {
        "base-400": "var(--base-400)",
        "zinc-900": "var(--zinc-900)",
        bug: "var(--bug)",
        dark: "var(--dark)",
        dragon: "var(--dragon)",
        electric: "var(--electric)",
        fairy: "var(--fairy)",
        fighting: "var(--fighting)",
        fire: "var(--fire)",
        flying: "var(--flying)",
        ghost: "var(--ghost)",
        grass: "var(--grass)",
        ground: "var(--ground)",
        ice: "var(--ice)",
        normal: "var(--normal)",
        poison: "var(--poison)",
        psychic: "var(--psychic)",
        rock: "var(--rock)",
        steel: "var(--steel)",
        water: "var(--water)",
      },
      screens: {
        xxl: "1480px",
      },
      keyframes: {
        "scale-up-down": {
          "0%": { transform: "scale(1)" },
          "50%": { transform: "scale(0.9)" },
          "100%": { transform: "scale(1)" },
        },
      },
    },
  },
  daisyui: {
    themes: [
      {
        light: {
          primary: "#be123c",
          secondary: "#d6d3d1",
          accent: "#e11d48",
          neutral: "#f2f2f2",
          "base-100": "#f2f2f2",
          "--base-400": "#bfbfbf",
          info: "#7dd3fc",
          success: "#22c55e",
          warning: "#fdba74",
          error: "#ef4444",
          "--zinc-900": "#18181b",
          "--bug": "#A8B820",
          "--dark": "#705848",
          "--dragon": "#7038F8",
          "--electric": "#F8D030",
          "--fairy": "#EE99AC",
          "--fighting": "#C03028",
          "--fire": "#F08030",
          "--flying": "#A890F0",
          "--ghost": "#705898",
          "--grass": "#78C850",
          "--ground": "#E0C068",
          "--ice": "#98D8D8",
          "--normal": "#A8A878",
          "--poison": "#A040A0",
          "--psychic": "#F85888",
          "--rock": "#B8A038",
          "--steel": "#B8B8D0",
          "--water": "#6890F0",
        },
      },
      {
        dark: {
          primary: "#be123c",
          secondary: "#d6d3d1",
          accent: "#e11d48",
          neutral: "#474151",
          "base-100": "#1f2937",
          "--base-400": "#121821",
          info: "#7dd3fc",
          success: "#22c55e",
          warning: "#fdba74",
          error: "#ef4444",
          "--zinc-900": "#18181b",

          "--bug": "#A8B820",
          "--dark": "#705848",
          "--dragon": "#7038F8",
          "--electric": "#F8D030",
          "--fairy": "#EE99AC",
          "--fighting": "#C03028",
          "--fire": "#F08030",
          "--flying": "#A890F0",
          "--ghost": "#705898",
          "--grass": "#78C850",
          "--ground": "#E0C068",
          "--ice": "#98D8D8",
          "--normal": "#A8A878",
          "--poison": "#A040A0",
          "--psychic": "#F85888",
          "--rock": "#B8A038",
          "--steel": "#B8B8D0",
          "--water": "#6890F0",
        },
      },
    ],
  },
  plugins: [require("daisyui")],
}
export default config
