export const maxPokemon = process.env.NEXT_PUBLIC_MAX_POKEMON ?? 151

export const specialPokemonNames: Record<string, string> = {
  "mr-mime": "Mr. Mime",
  "mime-jr": "Mime Jr.",
  "nidoran-f": "Nidoran ♀",
  "nidoran-m": "Nidoran ♂",
  "ho-oh": "Ho-Oh",
  "porygon-z": "Porygon-Z",
  farfetchd: "Farfetch'd",
  "deoxys-normal": "Deoxys",
  "darmanitan-standard": "Darmanitan",
  "wormadam-plant": "Wormadam",
  "keldeo-ordinary": "Keldeo",
  "giratina-altered": "Giratina",
  "shaymin-land": "Shaymin",
  "basculin-red-striped": "Basculin",
  "thundurus-incarnate": "Thundurus",
  "tornadus-incarnate": "Tornadus",
  "landorus-incarnate": "Landorus",
  "meloetta-aria": "Meloetta",
  "meowstic-male": "Meowstic ♂",
  "aegislash-shield": "Aegislash",
  "pumpkaboo-average": "Pumpkaboo",
  "gourgeist-average": "Gourgeist",
  "zygarde-50": "Zygarde",
  "hoopa-confined": "Hoopa",
  "oricorio-baile": "Oricorio",
  "lycanroc-midday": "Lycanroc",
  "wishiwashi-solo": "Wishiwashi",
  "minior-red-meteor": "Minior",
  "mimikyu-disguised": "Mimikyu",
  "necrozma-dusk": "Necrozma",
  "magearna-original": "Magearna",
  "toxtricity-amped": "Toxtricity",
  "eiscue-ice": "Eiscue",
  "type-null": "Type: Null",
  sirfetchd: "Sirfetch'd",
  "mr-rime": "Mr. Rime",
  "indeedee-male": "Indeedee ♂",
  "morpeko-full-belly": "Morpeko",
  "zacian-hero": "Zacian",
  "zamazenta-hero": "Zamazenta",
  "eternatus-eternamax": "Eternatus",
  "urshifu-single-strike": "Urshifu",
  "calyrex-ice-rider": "Calyrex",
  "calyrex-shadow-rider": "Calyrex",
  "basculegion-male": "Basculegion ♂",
  "enamorus-incarnate": "Enamorus",
}
